// Renders doc/CONFIG.md and .dev.vars.example from the schemas in src/env.ts
// (TIO-CFG-005, TIO-DEPLOY-008). Pure functions; scripts/gen-config-docs.ts writes the files.
import { z } from "zod";
import { EnvVarsSchema, SecretsSchema, SettingsSchema } from "../../src/config/schema.ts";

interface FieldDoc {
  name: string;
  type: string;
  fallback: string;
  bounds: string;
  description: string;
  required: boolean;
}

type JsonSchema = Record<string, unknown>;

function typeOf(schema: JsonSchema): string {
  if (Array.isArray(schema["enum"]))
    return (schema["enum"] as unknown[]).map((v) => `\`${JSON.stringify(v)}\``).join(" \\| ");
  if (Array.isArray(schema["anyOf"])) {
    return (schema["anyOf"] as JsonSchema[]).map(typeOf).join(" \\| ");
  }
  const type = schema["type"];
  if (Array.isArray(type)) return type.join(" \\| ");
  if (type === "array") return `array of ${typeOf((schema["items"] as JsonSchema) ?? {})}`;
  return String(type ?? "any");
}

function boundsOf(schema: JsonSchema): string {
  const parts: string[] = [];
  const inner = Array.isArray(schema["anyOf"])
    ? ((schema["anyOf"] as JsonSchema[])[0] ?? {})
    : schema;
  const min = inner["minimum"] as number | undefined;
  const max = inner["maximum"] as number | undefined;
  const safe = (n: number | undefined) =>
    n === undefined || Math.abs(n) === Number.MAX_SAFE_INTEGER;
  if (!(safe(min) && safe(max))) parts.push(`${safe(min) ? "−∞" : min}–${safe(max) ? "∞" : max}`);
  if (inner["minLength"] !== undefined || inner["maxLength"] !== undefined) {
    parts.push(`${inner["minLength"] ?? 0}–${inner["maxLength"] ?? "∞"} chars`);
  }
  return parts.join(", ");
}

function fieldDocs(schema: z.ZodObject): FieldDoc[] {
  const json = z.toJSONSchema(schema, { io: "input" }) as JsonSchema;
  const properties = json["properties"] as Record<string, JsonSchema>;
  const required = new Set((json["required"] as string[] | undefined) ?? []);
  return Object.entries(schema.shape).map(([name, field]) => {
    const property = properties[name] ?? {};
    const hasDefault = "default" in property;
    return {
      name,
      type: typeOf(property),
      fallback: hasDefault
        ? `\`${JSON.stringify(property["default"])}\``
        : required.has(name)
          ? "required"
          : "unset",
      bounds: boundsOf(property),
      description: (field as z.ZodType).description ?? "",
      required: required.has(name) && !hasDefault,
    };
  });
}

const table = (header: string[], rows: string[][]): string =>
  [
    `| ${header.join(" | ")} |`,
    `|${header.map(() => "---").join("|")}|`,
    ...rows.map((r) => `| ${r.join(" | ")} |`),
  ].join("\n");

export function renderConfigMarkdown(): string {
  const vars = fieldDocs(EnvVarsSchema);
  const secrets = fieldDocs(SecretsSchema);
  const settings = fieldDocs(SettingsSchema);
  return [
    "# Configuration",
    "",
    "Generated by `pnpm gen:config` from the schemas in `src/env.ts` (TIO-CFG-005). Do not edit by hand; CI fails when this file is stale.",
    "",
    "## Environment variables",
    "",
    "Set in `wrangler.jsonc` (`vars`), by the Deploy-to-Cloudflare form, or by the deploy environment for staging and production (spec §12.2).",
    "",
    table(
      ["Name", "Type", "Default", "Description"],
      vars.map((f) => [`\`${f.name}\``, f.type, f.fallback, f.description]),
    ),
    "",
    "## Secrets",
    "",
    "Worker secrets (`wrangler secret put`, the Deploy form, or `.dev.vars` locally). `pnpm gen:secrets` prints fresh values.",
    "",
    table(
      ["Name", "Required", "Description"],
      secrets.map((f) => [`\`${f.name}\``, f.required ? "yes" : "no", f.description]),
    ),
    "",
    "## Settings",
    "",
    "Runtime settings stored in the D1 `settings` table and edited through `PATCH /api/v1/admin/settings`; cached in each isolate for 60 s (TIO-ARCH-011). Every patch is validated as a whole (TIO-CFG-003).",
    "",
    table(
      ["Key", "Type", "Default", "Bounds", "Description"],
      settings.map((f) => [`\`${f.name}\``, f.type, f.fallback, f.bounds, f.description]),
    ),
    "",
  ].join("\n");
}

export function renderDevVarsExample(): string {
  const lines = [
    "# Secrets of a Tiny OIDC deployment. Copy to .dev.vars for `wrangler dev`;",
    "# the Deploy-to-Cloudflare form renders one field per entry. Generate values",
    "# with `pnpm gen:secrets`. Generated from src/env.ts by `pnpm gen:config`.",
    "",
  ];
  for (const secret of fieldDocs(SecretsSchema)) {
    lines.push(`# ${secret.description}${secret.required ? "" : " (optional)"}`);
    lines.push(`${secret.name}=`);
    lines.push("");
  }
  lines.push(
    "# Local development only: point the issuer at wrangler dev (uncomment).",
    "# ISSUER=http://localhost:8787",
    "# RP_ID=localhost",
    "",
  );
  return lines.join("\n");
}
