// Fresh secret values for the README steps and local development (TIO-DEPLOY-008).
import { webcrypto } from "node:crypto";

function random(bytes: number): Uint8Array {
  return webcrypto.getRandomValues(new Uint8Array(bytes));
}

export interface GeneratedSecrets {
  MASTER_KEYS: string;
  MASTER_KEY_ACTIVE: string;
  ADMIN_BOOTSTRAP_TOKEN: string;
}

export function generateSecrets(): GeneratedSecrets {
  return {
    MASTER_KEYS: JSON.stringify({ "1": Buffer.from(random(32)).toString("base64") }),
    MASTER_KEY_ACTIVE: "1",
    ADMIN_BOOTSTRAP_TOKEN: Buffer.from(random(32)).toString("base64url"),
  };
}

/** `.dev.vars` content for `wrangler dev` on the given local issuer. */
export function renderDevVars(secrets: GeneratedSecrets, issuer: string, rpId: string): string {
  return [
    "# Generated by `pnpm gen:secrets --dev-vars` for local development. Never commit.",
    `MASTER_KEYS=${secrets.MASTER_KEYS}`,
    `MASTER_KEY_ACTIVE=${secrets.MASTER_KEY_ACTIVE}`,
    `ADMIN_BOOTSTRAP_TOKEN=${secrets.ADMIN_BOOTSTRAP_TOKEN}`,
    `ISSUER=${issuer}`,
    `RP_ID=${rpId}`,
    "",
  ].join("\n");
}
